USE ESTACIONAMENTO;
DROP TABLE IF EXISTS TARIFA;
    
CREATE TABLE TARIFA (
	IDTARIFA INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    VALOR_HORA DECIMAL(10,2) NOT NULL,
    PRIMARY KEY(IDTARIFA)
    );

INSERT INTO TARIFA (NOME, VALOR_HORA) VALUES ('HORA', 5.00), ('DIARIA', 30.00), ('MENSAL', 250.00);

ALTER TABLE VEICULO
	ADD COLUMN IDTARIFA INT NOT NULL DEFAULT 1,
    ADD CONSTRAINT FK_VEICULO_TARIFA 
		FOREIGN KEY (IDTARIFA) REFERENCES TARIFA(IDTARIFA);
        
SELECT * FROM TARIFA;

INSERT INTO VEICULO (placa, hora_entrada, hora_saida, idtarifa) 
VALUES ('TEST001', NOW() - INTERVAL 2 HOUR, NULL, 1);

SELECT * FROM VEICULO;
DELETE FROM VEICULO WHERE IDVEICULO >= 3;
SELECT * FROM VEICULO;
DELETE FROM VEICULO WHERE IDVEICULO = 11;
